### ISSUE TITLE
Please add document about supporting Habror version range

### ISSUE THREAD

**Issue by tai-yi** [HylandSoftware/Harbor.Tagd#21]

**Comment by nlowe** [comment]
@tiayi Can you provide some more detail on this? Did you run into a compatibility issue of some sort? `tagd` should be compatible with all recent-ish versions of harbor (at least `1.4`+, probably works on `1.3` as well, I don't remember what version we were on when I started developing it)

**Comment by tai-yi** [comment]
I used a very old version 1.2x. You know, tagd doesn't support it.
But I have to try it out, then I know the result.
So, please add supporting versions in docs.

**Comment by nlowe** [comment]
Thanks for the info! I'll get the Readme updated. What error did you get? If it's something simple I may be able to add support for 1.2.

**Comment by tai-yi** [comment]
@nlowe , I think you don't need support 1.2x.
Harbor users update to newer version is better.
I already updated it to 1.7x.
I forgot the details about error. The reason is Harbor API breaking changes.
