### ISSUE TITLE
clean up for Helm charts

### ISSUE THREAD

**Issue by thatsk** [HylandSoftware/Harbor.Tagd#25]

**Comment by nlowe** [comment]
@thatsk Please leave a comment on goharbor/harbor#6654. For `tagd`, I'm not planning on adding any more major features as the plan is to move this functionality into harbor itself, but I would consider reviewing a pull request.

**Comment by nlowe** [comment]
Harbor 1.9 now includes a native tag retention feature, so I'm not currently planning on adding new features to `tagd`. Please open an issue on the Harbor project if you're looking for additional retention features.
